name: Deploy Azure Data Factory via Bicep

on:
  push:
    branches:
      - main  # or 'main' if that’s your default
    paths:
      - '**/*.bicep'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          resourceGroupName: rg-blobstorage
          template: ./main.bicep
          parameters: >
            factoryName=azure-quest
            BlobStorageLinkedService_conn='${{ secrets.BLOB_CONN_STRING }}'
      - name: Upload Databricks Notebook (.ipynb)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          pip install databricks-cli
      
          databricks workspace import \
            notebooks/my-notebook.ipynb \
            /Shared/my-notebook \
            --format JUPYTER \
            --language PYTHON \
            --overwrite